version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/fitness-tracking
      - JWT_SECRET_KEY=123456.
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4-bionic
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: